### ISSUE TITLE
Enhancement Request: Option to hide menu rather than navigating back

### ISSUE THREAD

**Issue by waseefakhtar** [saket/cascade#11]
I noticed that it currently navigates back from a submenu when clicked on an item. What about adding an option to hide the menu altogether rather than navigating back?

### Demo:
<img src="https://user-images.githubusercontent.com/4093820/95676948-8b6f4280-0bdb-11eb-8141-1e4ea91dd929.gif" width="300"/>

**Comment by saket** [comment]
Oh yeah item clicks will always dismiss the menu. The sample app intentionally navigates back instead: https://github.com/saket/cascade/blob/891031ab4d52dc00f41fdb0fb1e094279e92143c/sample/src/main/java/me/saket/cascade/sample/MainActivity.kt#L82-L87
