### ISSUE TITLE
Setting visibility to false shows an empty item

### ISSUE THREAD

**Issue by waseefakhtar** [saket/cascade#12]
Setting visibility to false currently functions like View.INVISIBLE and not View.GONE.

### Demo
<img src="https://user-images.githubusercontent.com/4093820/95677001-ff114f80-0bdb-11eb-9987-ddcc1685c4ad.png" width="300"/>

**Comment by saket** [comment]
Interesting. Filtering out invisible items in the list should be easy and should only require an `if` condition here: https://github.com/saket/cascade/blob/891031ab4d52dc00f41fdb0fb1e094279e92143c/cascade/src/main/java/me/saket/cascade/CascadeMenuAdapter.kt#L38

Wanna send a PR?

**Comment by waseefakhtar** [comment]
Sure :)
