### ISSUE TITLE
Support menu appearing from bottom of screen

### ISSUE THREAD

**Issue by ac87** [saket/cascade#15]
Great looking library, can see it being desirable to have these menus popup from the bottom of the screen, nearer the users normal reach.

Currently with the sample app if you move the toolbar to the bottom the menu appears but only showing the first item.

![image](https://user-images.githubusercontent.com/20557626/95991885-3a528f00-0e25-11eb-876e-afba936ac17d.png)

**Comment by bohsen** [comment]
Could probably be fixed using [this](https://stackoverflow.com/a/52768403/1495686)

**Comment by saket** [comment]
Let's merge this issue with #21
