### ISSUE TITLE
Unable to use cascade from java

### ISSUE THREAD

**Issue by paramrana78** [saket/cascade#17]
All files are in kotlin, I want a java version for the same.

**Comment by saket** [comment]
@paramrana78 what's missing in cascade that's preventing you from using it from java?

**Comment by paramrana78** [comment]
> @paramrana78 what's missing in cascade that's preventing you from using it from java?

@saket  Sir, thanks for your response and update. I have few projects that only use java not kotlin so I was trying to implement it without using kotlin compile libraries in gradle files!! I hope you understand my point.

**Comment by saket** [comment]
What's stopping you from adding Kotlin to your project? [It is the way](https://i.imgur.com/YuzwJr7.jpg) forward for developing Android apps so you're going to have a really hard time trying to avoid it. You don't even have to convert your Java source into Kotlin for consuming libraries written in Kotlin.

I'm marking this as closed as this isn't really an issue with cascade, but feel free to continue this conversation here.

**Comment by paramrana78** [comment]
@saket  ok then you mean I have to convert the pending java projects with the kotlin support. I will inform you if I am facing any issue regarding the same. Thanks
