### ISSUE TITLE
Allow setting of max width

### ISSUE THREAD

**Issue by Kev1000000** [saket/cascade#19]
I'd love if I could set the max width of the PopupMenu to something dynamic so I can accommodate slightly larger strings of text while using icons.

**Comment by saket** [comment]
Is this what you're looking for?

https://github.com/saket/cascade/blob/79ace480f33bc7cd2726db5022c099deeb54d9c4/cascade/src/main/java/me/saket/cascade/CascadePopupMenu.kt#L35

**Comment by Kev1000000** [comment]
Ah yes, perfect!
