### ISSUE TITLE
App Crashing when click to open the popup

### ISSUE THREAD

**Issue by Mohamadkotb** [saket/cascade#20]
App Crashing when click to open the popup
Android 5.1

Here are logs:
`

> 10-27 14:15:18.168 19215-19215/com.myprohelper.staging E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.myprohelper.staging, PID: 19215
>     java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
>         at me.saket.cascade.CascadePopupWindow.runWithMargins(CascadePopupWindow.kt:103)
>         at me.saket.cascade.CascadePopupWindow.showAsDropDown(CascadePopupWindow.kt:89)
>         at me.saket.cascade.CascadePopupMenu.show(CascadePopupMenu.kt:73)
>         at com.myprohelper.ui.base.tableview.TableViewListener.onRowHeaderClicked(TableViewListener.kt:49)
>         at com.evrencoskun.tableview.listener.itemclick.RowHeaderRecyclerViewItemClickListener.clickAction(RowHeaderRecyclerViewItemClickListener.java:59)
>         at com.evrencoskun.tableview.listener.itemclick.AbstractItemClickListener$1.onSingleTapConfirmed(AbstractItemClickListener.java:65)
>         at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:295)
>         at android.os.Handler.dispatchMessage(Handler.java:111)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:6102)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:372)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

**Comment by Kev1000000** [comment]
Yep, also receiving this on Android 5.x

**Comment by thomaspoulainconsulting** [comment]
Same here in prod, mostly in Android 5.1.1 with Samsung Galaxy Tab4 Active, is it possible to investigate on that issue ? :)

**Comment by saket** [comment]
Fixed with [v1.2.0](https://github.com/saket/cascade/releases/tag/1.2.0). Thank you for reporting this!
