### ISSUE TITLE
Android 5 issues

### ISSUE THREAD

**Issue by MohamedHarmoush** [saket/cascade#22]
Hi @saket 
I hope you're doing well. Thanks for that great library.

I notice some issues in android 5

- Can't do any action while the popup menu is opened
- The popup looks very strange when clicking on the bottom of the screen
- When open the keyboard the popup menu is jumped to the top of the screen
Please, check the attached images

![received_441420143687499](https://user-images.githubusercontent.com/17739421/100796990-204b2b00-342a-11eb-91b8-d3114fd39329.jpg)
![received_411103146927199](https://user-images.githubusercontent.com/17739421/100796994-217c5800-342a-11eb-9733-f3bd42c82604.jpg)
![received_978552435973192](https://user-images.githubusercontent.com/17739421/100796995-2214ee80-342a-11eb-882e-d9b86bf37edc.jpg)
![received_197330485325167](https://user-images.githubusercontent.com/17739421/100796996-2214ee80-342a-11eb-8c2c-ab52f722c8b6.jpg)

**Comment by saket** [comment]
> Can't do any action while the popup menu is opened

Probably another API 21 weirdness. Investigating and debugging API 21 issues are a lot of pain. I'm considering bumping cascade's minSdk to 23+.

> The popup looks very strange when clicking on the bottom of the screen

This might be related to https://github.com/saket/cascade/issues/21

> When open the keyboard the popup menu is jumped to the top of the screen

I'll try investigating this.

**Comment by saket** [comment]
Closing this because cascade's minSdk was bumped to 23 in [2.0.0](https://github.com/saket/cascade/releases/tag/2.0.0-rc01).
