### ISSUE TITLE
Expand to up ?

### ISSUE THREAD

**Issue by zahidcataltas** [saket/cascade#26]
How do I make it open upwards when I click on a view at the bottom of the screen?

**Comment by saket** [comment]
Is this a duplicate of https://github.com/saket/cascade/issues/21?

**Comment by zahidcataltas** [comment]
I'm not sure.
Now like this:
![00](https://user-images.githubusercontent.com/23355390/143446980-7637f3ae-af0c-44b1-ba0b-7546b6b02003.gif)
I need:
![qq](https://user-images.githubusercontent.com/23355390/143447004-127b99f1-1d4b-4c6a-86ff-bb2580477a97.gif)

**Comment by zahidcataltas** [comment]
And yes I guess same problem with #15  . Sorry for being repetitive.

**Comment by saket** [comment]
Closing this in favor of #15.
