### ISSUE TITLE
add some view when show popup like reaction...

### ISSUE THREAD

**Issue by fukemy** [saket/cascade#32]
Hi, thanks for great library, did u tend to support some view like reaction Messenger, Telegram... like below?

**Comment by waseefakhtar** [comment]
Definitely something we should have but that makes a library on its own. The idea of cascade is to help implement nested popup menus with intuitive navigation. So don't think this is the scope of this library, unless @saket has other thoughts. 🙂

**Comment by saket** [comment]
Same thought! This looks unrelated to cascade.
