### ISSUE TITLE
Opens submenu multiple times if you click a child multiple times

### ISSUE THREAD

**Issue by MV-GH** [saket/cascade#41]
*I am double clicking on that DropdownMenuItem which opens that submenu twice*
![vmOM9iOO5C](https://github.com/saket/cascade/assets/67873169/23395844-381c-4d4c-96c8-317af06e7108)

**Comment by MV-GH** [comment]
This is not fixed, I can still reproduce this with 2.3.0

**Comment by MV-GH** [comment]
Because I assume

```kt
  internal fun navigateTo(entry: CascadeBackStackEntry) {
    if (entry != backStack.lastOrNull()) {
      backStack.add(entry)
    }
  }
  ``` 

Each time I click, it creates another class thus the comparison fails, as its unique each time

**Comment by saket** [comment]
Serves me right for not adding an automated test for this 🙂. Let me fix this (again).
