### ISSUE TITLE
When there is insufficient space on the screen, the Popup is displayed incompletely or even becomes invisible.

### ISSUE THREAD

**Issue by Merpyzf** [saket/cascade#50]
When there is a button at the bottom of the screen and clicking on it triggers a Popup, the Popup is not fully displayed. In some extreme cases, the Popup is even invisible. I have confirmed that this issue is caused by setting the Popup height to **WRAP_CONTENT**.

![Screenshot_20240103_201714](https://github.com/saket/cascade/assets/20330390/778f4e0a-bbc2-4e7f-9311-9c5add3aa5db)

when I specified the exact height for the Popup, the issue was resolved. (I manually measured the height of each item in the RecyclerView).

```
   popup.width = fixedWidth
   popup.height = **measureHeightOfChildrenCompat(maxHeight)** + context.dip(4) // Doesn't work on API 21 without this.
    
   popup.showAsDropDown(anchor, 0, 0, gravity)
```
![Screenshot_20240103_202253](https://github.com/saket/cascade/assets/20330390/a769a219-7f1a-4451-b42a-bf94a40e3146)

**Comment by saket** [comment]
Was this accidentally closed?
